AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tags:
      project: "AWS Whats New"
    Runtime: python3.10
    Architectures:
      - arm64

Parameters:
    StageEnv:
      Type: String
      AllowedValues:
        - dev
        - prod

Mappings:
  StageMappings:
    dev:
      stage: dev
    prod:
      stage: prod

Resources:
  AwsWhatsNew:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.lambda_handler
      CodeUri: ./
      Timeout: 200
      Environment:
        Variables:
          PostsTableName: !Ref AwsNewsRecentPostsTable
          PostRecencyThreshold: "7000"
          stage: !FindInMap [StageMappings, !Ref StageEnv, stage]
      ReservedConcurrentExecutions: 1
      Events:
        CheckForNewPostsScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AwsNewsRecentPostsTable
        - Statement:
          -
            Effect: "Allow"
            Action:
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Resource:
              - '*'
              - 'arn:aws:ssm:::parameter/whatsnew/*'
  AwsNewsRecentPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: guid
          AttributeType: S
      KeySchema:
        - AttributeName: guid
          KeyType: HASH
      Tags:
        - Value: "AWS Whats New"
          Key: "app"